use_frameworks!

target 'zkqPrivateSpec_Example' do
  pod 'zkqPrivateSpec', :path => '../'

  target 'zkqPrivateSpec_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
